# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(default='', max_length=50)),
                ('doctor', models.CharField(default='', max_length=50)),
                ('reason', models.TextField(default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='endUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.CharField(blank=True, max_length=10, null=True)),
                ('PhoneNumber', models.IntegerField(blank=True, null=True)),
                ('State', models.CharField(blank=True, default='', max_length=30)),
                ('City', models.CharField(blank=True, default='', max_length=50)),
                ('Address', models.CharField(blank=True, default='', max_length=50)),
                ('ZipCode', models.IntegerField(blank=True, null=True)),
                ('ECFirstName', models.CharField(blank=True, default='', max_length=25)),
                ('ECLastName', models.CharField(blank=True, default='', max_length=25)),
                ('ECPhoneNumber', models.IntegerField(blank=True, null=True)),
                ('isNurse', models.BooleanField(default=False)),
                ('isDoctor', models.BooleanField(default=False)),
                ('isAdministrator', models.BooleanField(default=False)),
                ('isPatient', models.BooleanField(default=False)),
                ('isSecretary', models.BooleanField(default=False)),
                ('Doc', models.TextField(blank=True, default='')),
                ('Prescriptions', models.TextField(blank=True, default='', max_length=1000)),
                ('ProviderID', models.IntegerField(blank=True, null=True)),
                ('PolicyType', models.CharField(blank=True, default='', max_length=25)),
                ('PolicyNumber', models.IntegerField(blank=True, null=True)),
                ('records', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('isAdmitted', models.BooleanField(default=False)),
                ('aReason', models.CharField(blank=True, default='', max_length=100)),
                ('aCount', models.IntegerField(blank=True, default=0)),
                ('aTime', models.DateTimeField(blank=True, null=True)),
                ('OCPhoneNumber', models.IntegerField(blank=True, null=True)),
                ('Patients', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients', models.TextField(default='')),
                ('doctors', models.TextField(default='')),
                ('nurses', models.TextField(default='')),
                ('secretaries', models.TextField(default='')),
                ('admins', models.TextField(default='')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Address', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='an event happened', max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.endUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=50)),
                ('reciever', models.CharField(default='', max_length=50)),
                ('message', models.TextField(blank=True, default='', max_length=1000)),
                ('subject', models.CharField(default='', max_length=100)),
                ('timeSent', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='perscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(default='', max_length=50)),
                ('doctor', models.CharField(default='', max_length=50)),
                ('perscription', models.CharField(default='', max_length=50)),
                ('dose', models.CharField(default='', max_length=50)),
                ('reason', models.TextField(default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fn', models.CharField(default='', max_length=50)),
                ('patient_fn', models.CharField(default='', max_length=50)),
                ('pending', models.BooleanField(default=True)),
                ('information', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('results', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fn', models.CharField(default='', max_length=50)),
                ('patient_fn', models.CharField(default='', max_length=50)),
                ('pending', models.BooleanField(default=True)),
                ('information', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('results', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
    ]
