# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 21:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begins', models.DateTimeField(default=datetime.datetime(2016, 12, 5, 16, 52, 23, 808952))),
                ('doctorID', models.IntegerField(null=True)),
                ('patientID', models.IntegerField(null=True)),
                ('length', models.DurationField(default=datetime.timedelta(0, 2700))),
                ('location', models.TextField(default='', max_length=80)),
                ('day', models.IntegerField(default=5)),
                ('month', models.IntegerField(default=12)),
                ('year', models.IntegerField(default=2016)),
            ],
        ),
    ]
